### PR TITLE
Added helper function toOriginalFieldFromAlias

### PR DESCRIPTION
**Pull request by adamlc**
Added a function that can be used to convert the field name of a single aliased field. This can be useful when building queries etc

### CODE REVIEW

**Comment by ramiel** [comment]
Very useful! Please, can you make the PR against `develop` instead of `mater`? (I changed the default branch to avoid this problem again, sorry!

**Comment by adamlc** [comment]
@ramiel no problem! I've changed the base, hopefully won't need to rebase :)

**Comment by ramiel** [comment]
@adamlc Published in version 0.2.0

**Comment by adamlc** [comment]
Awesome thanks!

**Pull request merged**
